### ISSUE TITLE
APIの選定

### ISSUE THREAD

**Issue by ostk0069** [CATechAccel/Colombia#2]
## 行うこと
- [ ] 何かをテーマに一覧でその情報を受け取れるAPI
    - アニメ、映画、ニュース、テレビ番組
    - 特になかった場合や困った場合は[Annict Developers](https://developers.annict.jp/)を使う

## 参考
- 

## 関連Issues
-

**Comment by nayutaroo** [comment]
Annict Developersを採用します。
